USE ROLE ACCOUNTADMIN;
USE WAREHOUSE BANKING_A;
USE DATABASE BANKDB;
USE SCHEMA BANKDB.BANKSCHEMA;

SHOW COLUMNS IN UNIFIED_BANK_DATA;

// Number of monthly transactions
CREATE OR REPLACE VIEW V_MONTHLY_TRANSACTIONS AS SELECT DATE_TRUNC('MONTH', TRANSACTION_DATE) AS MONTH, COUNT(*) AS TOTAL_TRANSACTIONS FROM UNIFIED_BANK_DATA GROUP BY MONTH ORDER BY MONTH;
SELECT * FROM V_MONTHLY_TRANSACTIONS;

// City wise average balance
CREATE OR REPLACE VIEW V_HIGHEST_AVG_BAL_CITY AS SELECT CITY, AVG(ACCOUNT_BALANCE_AFTER_TRANSACTION) AS AVG_ACCOUNT_BALANCE, COUNT(CUSTOMER_ID) AS CUSTOMER_COUNT FROM UNIFIED_BANK_DATA GROUP BY CITY;
SELECT * FROM V_HIGHEST_AVG_BAL_CITY;

// Which branch generates more loan
CREATE OR REPLACE VIEW V_BRANCH_WITH_MOST_LOAN AS SELECT BRANCH_ID, COUNT(LOAN_ID) AS TOTAL_LOANS, SUM(LOAN_AMOUNT) AS TOTAL_LOAN_AMOUNT, AVG(LOAN_AMOUNT) AS AVG_LOAN_AMOUNT FROM UNIFIED_BANK_DATA WHERE UPPER(LOAN_STATUS) IN ('APPROVED', 'CLOSED') GROUP BY BRANCH_ID;
SELECT * FROM V_BRANCH_WITH_MOST_LOAN;

// Most popular account type
CREATE OR REPLACE VIEW V_POPULAR_ACC_TYPE AS SELECT ACCOUNT_TYPE, COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMERS, AVG(ACCOUNT_BALANCE) AS AVG_BALANCE, SUM(ACCOUNT_BALANCE) AS TOTAL_BALANCE FROM UNIFIED_BANK_DATA GROUP BY ACCOUNT_TYPE;
SELECT * FROM V_POPULAR_ACC_TYPE;

// What is the average interest rate charged across different loan products?
CREATE OR REPLACE VIEW V_AVG_INTEREST_PRODUCT AS SELECT LOAN_TYPE, AVG(INTEREST_RATE) AS AVG_INTEREST_RATE FROM UNIFIED_BANK_DATA GROUP BY LOAN_TYPE ORDER BY AVG_INTEREST_RATE DESC;
SELECT * FROM V_AVG_INTEREST_PRODUCT;

SELECT * FROM UNIFIED_BANK_DATA;
