USE ROLE ACCOUNTADMIN;
USE WAREHOUSE BANKING_A;
USE DATABASE BANKDB;
USE SCHEMA BANKDB.BANKSCHEMA;

SELECT * FROM BANKING_DATA_RAW LIMIT 10;

// Check Columns
DESC TABLE BANKING_DATA_RAW;

CREATE OR REPLACE TABLE CUSTOMER AS SELECT CUSTOMER_ID, FULL_NAME, AGE, GENDER, ADDRESS, CITY, CONTACT_NUMBER, EMAIL, ACCOUNT_TYPE, ACCOUNT_BALANCE, DATE_OF_ACCOUNT_OPENING, ANOMALY FROM BANKING_DATA_RAW;

CREATE OR REPLACE TABLE TRANSACTION_TABLE AS SELECT TRANSACTIONID, CUSTOMER_ID, LAST_TRANSACTION_DATE, TRANSACTION_DATE, TRANSACTION_TYPE, TRANSACTION_AMOUNT, ACCOUNT_BALANCE_AFTER_TRANSACTION, ANOMALY FROM BANKING_DATA_RAW;

CREATE OR REPLACE TABLE LOAN AS SELECT LOAN_ID, CUSTOMER_ID, BRANCH_ID, LOAN_AMOUNT, LOAN_TYPE, INTEREST_RATE, LOAN_TERM, APPROVAL_REJECTION_DATE, LOAN_STATUS, CARDID, CARD_TYPE, CREDIT_LIMIT, CREDIT_CARD_BALANCE, MINIMUM_PAYMENT_DUE, PAYMENT_DUE_DATE, LAST_CREDIT_CARD_PAYMENT_DATE, REWARDS_POINTS, ANOMALY FROM BANKING_DATA_RAW;

ALTER TABLE CUSTOMER ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY(CUSTOMER_ID);

ALTER TABLE TRANSACTION_TABLE ADD CONSTRAINT PK_TRANSACTION PRIMARY KEY(TRANSACTIONID);
ALTER TABLE TRANSACTION_TABLE ADD CONSTRAINT FK_TRANSACTION FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);

ALTER TABLE LOAN ADD CONSTRAINT PK_LOAN PRIMARY KEY(LOAN_ID);
ALTER TABLE LOAN ADD CONSTRAINT FK_LOAN FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);

// Validating Tables
SELECT COUNT(*) AS CUSTOMER_COUNT FROM CUSTOMER;
SELECT COUNT(*) AS TRANSACTION_COUNT FROM TRANSACTION_TABLE;
SELECT COUNT(*) AS LOAN_COUNT FROM LOAN;