USE ROLE ACCOUNTADMIN;
USE WAREHOUSE BANKING_A;
USE DATABASE BANKDB;
USE SCHEMA BANKDB.BANKSCHEMA;

-- HIGH VALUE CUSTOMERS - 414
CREATE OR REPLACE TABLE HIGH_VALUE_CUSTOMERS AS 
    SELECT * FROM UNIFIED_BANK_DATA 
    WHERE 
    (ANOMALY = FALSE AND
    CREDIT_UTILIZATION_PERCENTAGE <= 10.0 AND
    ACCOUNT_BALANCE >= (SELECT ACCOUNT_BALANCE_P75 FROM CUSTOMER_SEGMENT_THRESHOLDS) AND
    REWARDS_POINTS >= (SELECT REWARDS_POINTS_P75 FROM CUSTOMER_SEGMENT_THRESHOLDS) AND
    (UPPER(LOAN_STATUS) = 'APPROVED' OR UPPER(LOAN_STATUS) = 'CLOSED')
    )
    OR
    (ANOMALY = FALSE AND 
    UPPER(TRANSACTION_TYPE) = 'DEPOSIT'
    AND TRANSACTION_AMOUNT >= (SELECT PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY TRANSACTION_AMOUNT) FROM UNIFIED_BANK_DATA WHERE UPPER(TRANSACTION_TYPE) = 'DEPOSIT')
    );

SELECT * FROM HIGH_VALUE_CUSTOMERS;

SELECT * FROM  LOAN WHERE CREDIT_UTILIZATION_PERCENTAGE >= 30.0 AND CREDIT_UTILIZATION_PERCENTAGE <= 50.0;

-- RISKY VALUE CUSTOMERS - 1790
CREATE OR REPLACE TABLE RISKY_CUSTOMERS AS SELECT * FROM UNIFIED_BANK_DATA
WHERE (
    ANOMALY = TRUE
    OR CREDIT_UTILIZATION_PERCENTAGE >= 80
    )
    OR 
    ((
    CASE WHEN CREDIT_UTILIZATION_PERCENTAGE >= 70 THEN 1 ELSE 0 END +
    CASE WHEN MINIMUM_PAYMENT_DUE > ((CREDIT_CARD_BALANCE*5)/100) THEN 1 ELSE 0 END +
    CASE WHEN ((CREDIT_CARD_BALANCE + LOAN_AMOUNT)/ACCOUNT_BALANCE)*100 >= (SELECT MONEY_ISSUES_P75 FROM CUSTOMER_SEGMENT_THRESHOLDS) THEN 1 ELSE 0 END
    ) >= 2
);

SELECT * FROM RISKY_CUSTOMERS;

-- LOAN ELIGIBLE CUSTOMERS - 576
CREATE OR REPLACE TABLE LOAN_ELIGIBLE AS
    SELECT * FROM UNIFIED_BANK_DATA
    WHERE ANOMALY = FALSE AND
    CREDIT_UTILIZATION_PERCENTAGE <= 30 AND
    (UPPER(LOAN_STATUS) = 'APPROVED' OR UPPER(LOAN_STATUS) = 'CLOSED') AND
    LAST_TRANSACTION_DATE >= (SELECT DATEADD(YEAR, -1, MAX(LAST_TRANSACTION_DATE)) FROM UNIFIED_BANK_DATA) AND
    ACCOUNT_BALANCE >= (SELECT MEDIAN(ACCOUNT_BALANCE) FROM UNIFIED_BANK_DATA);

SELECT * FROM LOAN_ELIGIBLE;

-- WARNING CUSTOMERS - 1941
CREATE OR REPLACE TABLE WARNING_CUSTOMERS AS
    SELECT * FROM UNIFIED_BANK_DATA
    WHERE ANOMALY = FALSE AND
    (
    (CREDIT_UTILIZATION_PERCENTAGE > 30 AND CREDIT_UTILIZATION_PERCENTAGE < 50) OR
    ACCOUNT_BALANCE < (SELECT ACCOUNT_BALANCE_P25 FROM CUSTOMER_SEGMENT_THRESHOLDS) OR
    LAST_TRANSACTION_DATE < (SELECT DATEADD(YEAR, -1, MAX(LAST_TRANSACTION_DATE)) FROM UNIFIED_BANK_DATA)
    )

SELECT * FROM WARNING_CUSTOMERS;

// Overlapping customers
// risky_customers and high_value_customers - 103
SELECT CUSTOMER_ID FROM UNIFIED_BANK_DATA
WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM high_value_customers)
AND CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM risky_customers);

// risky_customers and loan_eligible - 0
SELECT CUSTOMER_ID FROM UNIFIED_BANK_DATA
WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM loan_eligible)
AND CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM risky_customers);

// risky_customers and warning_customers - 616
SELECT CUSTOMER_ID FROM UNIFIED_BANK_DATA
WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM warning_customers)
AND CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM risky_customers);

// warning_customers and loan_eligible - 0
SELECT CUSTOMER_ID FROM UNIFIED_BANK_DATA
WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM warning_customers)
AND CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM loan_eligible);

// warning_customers and high_value_customers - 166
SELECT CUSTOMER_ID FROM UNIFIED_BANK_DATA
WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM warning_customers)
AND CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM high_value_customers);

// loan_eligible and high_value_customers - 67
SELECT CUSTOMER_ID FROM UNIFIED_BANK_DATA
WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM high_value_customers)
AND CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM loan_eligible);

// Labelling the customers - high_value, loan_eligible, risky_customers, warning_customers, normal
ALTER TABLE UNIFIED_BANK_DATA ADD COLUMN CUSTOMER_TYPE ARRAY;
UPDATE UNIFIED_BANK_DATA SET CUSTOMER_TYPE = CASE
    WHEN CUSTOMER_ID NOT IN (
            SELECT CUSTOMER_ID FROM RISKY_CUSTOMERS
        )
     AND CUSTOMER_ID NOT IN (
            SELECT CUSTOMER_ID FROM HIGH_VALUE_CUSTOMERS
        )
     AND CUSTOMER_ID NOT IN (
            SELECT CUSTOMER_ID FROM LOAN_ELIGIBLE
        )
     AND CUSTOMER_ID NOT IN (
            SELECT CUSTOMER_ID FROM WARNING_CUSTOMERS
        )
    THEN ARRAY_CONSTRUCT('NORMAL')

    ELSE ARRAY_COMPACT(
            ARRAY_CONSTRUCT(
                CASE WHEN CUSTOMER_ID IN (
                    SELECT CUSTOMER_ID FROM RISKY_CUSTOMERS
                ) THEN 'RISKY' END,

                CASE WHEN CUSTOMER_ID IN (
                    SELECT CUSTOMER_ID FROM HIGH_VALUE_CUSTOMERS
                ) THEN 'HIGH_VALUE' END,

                CASE WHEN CUSTOMER_ID IN (
                    SELECT CUSTOMER_ID FROM LOAN_ELIGIBLE
                ) THEN 'LOAN_ELIGIBLE' END,

                CASE WHEN CUSTOMER_ID IN (
                    SELECT CUSTOMER_ID FROM WARNING_CUSTOMERS
                ) THEN 'WARNING' END
            )
         )
END;

SELECT CUSTOMER_ID, FULL_NAME, CUSTOMER_TYPE FROM UNIFIED_BANK_DATA;