USE ROLE ACCOUNTADMIN;
USE WAREHOUSE BANKING_A;
USE DATABASE BANKDB;
USE SCHEMA BANKDB.BANKSCHEMA;

SELECT * FROM BANKING_DATA_RAW LIMIT 10;

// ETL(Extract Transform Load Operation)

// Checking NULL values in the table - Method 1
SELECT * FROM BANKING_DATA_RAW WHERE
    Customer_ID IS NULL OR
    First_Name IS NULL OR
    Last_Name IS NULL OR
    Age IS NULL OR
    Gender IS NULL OR
    Address IS NULL OR
    City IS NULL OR
    Contact_Number IS NULL OR
    Email IS NULL OR
    Account_Type IS NULL OR
    Account_Balance IS NULL OR
    Date_Of_Account_Opening IS NULL OR
    Last_Transaction_Date IS NULL OR
    TransactionID IS NULL OR
    Transaction_Date IS NULL OR
    Transaction_Type IS NULL OR
    Transaction_Amount IS NULL OR
    Account_Balance_After_Transaction IS NULL OR
    Branch_ID IS NULL OR
    Loan_ID IS NULL OR
    Loan_Amount IS NULL OR
    Loan_Type IS NULL OR
    Interest_Rate IS NULL OR
    Loan_Term IS NULL OR
    Approval_Rejection_Date IS NULL OR
    Loan_Status IS NULL OR
    CardID IS NULL OR
    Card_Type IS NULL OR
    Credit_Limit IS NULL OR
    Credit_Card_Balance IS NULL OR
    Minimum_Payment_Due IS NULL OR
    Payment_Due_Date IS NULL OR
    Last_Credit_Card_Payment_Date IS NULL OR
    Rewards_Points IS NULL OR
    Feedback_ID IS NULL OR
    Feedback_Date IS NULL OR
    Feedback_Type IS NULL OR
    Resolution_Status IS NULL OR
    Resolution_Date IS NULL OR
    Anomaly IS NULL;

// Checking NULL values in the table - Method 2
SELECT
    'SELECT ' ||
    LISTAGG(
        'SUM(CASE WHEN ' || COLUMN_NAME || ' IS NULL THEN 1 ELSE 0 END) AS ' || COLUMN_NAME || '_nulls',
        ', '
    )
    || ' FROM banking_data_raw;'
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'BANKING_DATA_RAW'
  AND TABLE_SCHEMA = 'BANKSCHEMA'
  AND TABLE_CATALOG = 'BANKDB';

SELECT SUM(CASE WHEN FEEDBACK_TYPE IS NULL THEN 1 ELSE 0 END) AS FEEDBACK_TYPE_nulls, SUM(CASE WHEN LAST_CREDIT_CARD_PAYMENT_DATE IS NULL THEN 1 ELSE 0 END) AS LAST_CREDIT_CARD_PAYMENT_DATE_nulls, SUM(CASE WHEN CARDID IS NULL THEN 1 ELSE 0 END) AS CARDID_nulls, SUM(CASE WHEN BRANCH_ID IS NULL THEN 1 ELSE 0 END) AS BRANCH_ID_nulls, SUM(CASE WHEN ACCOUNT_BALANCE_AFTER_TRANSACTION IS NULL THEN 1 ELSE 0 END) AS ACCOUNT_BALANCE_AFTER_TRANSACTION_nulls, SUM(CASE WHEN FULL_NAME_FLAG IS NULL THEN 1 ELSE 0 END) AS FULL_NAME_FLAG_nulls, SUM(CASE WHEN LOAN_STATUS IS NULL THEN 1 ELSE 0 END) AS LOAN_STATUS_nulls, SUM(CASE WHEN TRANSACTIONID IS NULL THEN 1 ELSE 0 END) AS TRANSACTIONID_nulls, SUM(CASE WHEN TRANSACTION_AMOUNT IS NULL THEN 1 ELSE 0 END) AS TRANSACTION_AMOUNT_nulls, SUM(CASE WHEN DATE_OF_ACCOUNT_OPENING IS NULL THEN 1 ELSE 0 END) AS DATE_OF_ACCOUNT_OPENING_nulls, SUM(CASE WHEN RESOLUTION_DATE IS NULL THEN 1 ELSE 0 END) AS RESOLUTION_DATE_nulls, SUM(CASE WHEN FEEDBACK_ID IS NULL THEN 1 ELSE 0 END) AS FEEDBACK_ID_nulls, SUM(CASE WHEN LAST_TRANSACTION_DATE IS NULL THEN 1 ELSE 0 END) AS LAST_TRANSACTION_DATE_nulls, SUM(CASE WHEN PAYMENT_DUE_DATE IS NULL THEN 1 ELSE 0 END) AS PAYMENT_DUE_DATE_nulls, SUM(CASE WHEN LOAN_TYPE IS NULL THEN 1 ELSE 0 END) AS LOAN_TYPE_nulls, SUM(CASE WHEN CARD_TYPE IS NULL THEN 1 ELSE 0 END) AS CARD_TYPE_nulls, SUM(CASE WHEN TRANSACTION_DATE IS NULL THEN 1 ELSE 0 END) AS TRANSACTION_DATE_nulls, SUM(CASE WHEN TRANSACTION_TYPE IS NULL THEN 1 ELSE 0 END) AS TRANSACTION_TYPE_nulls, SUM(CASE WHEN CREDIT_CARD_BALANCE IS NULL THEN 1 ELSE 0 END) AS CREDIT_CARD_BALANCE_nulls, SUM(CASE WHEN ACCOUNT_TYPE IS NULL THEN 1 ELSE 0 END) AS ACCOUNT_TYPE_nulls, SUM(CASE WHEN FEEDBACK_DATE IS NULL THEN 1 ELSE 0 END) AS FEEDBACK_DATE_nulls, SUM(CASE WHEN INTEREST_RATE IS NULL THEN 1 ELSE 0 END) AS INTEREST_RATE_nulls, SUM(CASE WHEN LOAN_AMOUNT IS NULL THEN 1 ELSE 0 END) AS LOAN_AMOUNT_nulls, SUM(CASE WHEN EMAIL IS NULL THEN 1 ELSE 0 END) AS EMAIL_nulls, SUM(CASE WHEN CITY IS NULL THEN 1 ELSE 0 END) AS CITY_nulls, SUM(CASE WHEN LOAN_ID IS NULL THEN 1 ELSE 0 END) AS LOAN_ID_nulls, SUM(CASE WHEN GENDER IS NULL THEN 1 ELSE 0 END) AS GENDER_nulls, SUM(CASE WHEN LOAN_TERM IS NULL THEN 1 ELSE 0 END) AS LOAN_TERM_nulls, SUM(CASE WHEN REWARDS_POINTS IS NULL THEN 1 ELSE 0 END) AS REWARDS_POINTS_nulls, SUM(CASE WHEN CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) AS CUSTOMER_ID_nulls, SUM(CASE WHEN MINIMUM_PAYMENT_DUE_FLAG IS NULL THEN 1 ELSE 0 END) AS MINIMUM_PAYMENT_DUE_FLAG_nulls, SUM(CASE WHEN ADDRESS IS NULL THEN 1 ELSE 0 END) AS ADDRESS_nulls, SUM(CASE WHEN ACCOUNT_BALANCE_FLAG IS NULL THEN 1 ELSE 0 END) AS ACCOUNT_BALANCE_FLAG_nulls, SUM(CASE WHEN ACCOUNT_BALANCE IS NULL THEN 1 ELSE 0 END) AS ACCOUNT_BALANCE_nulls, SUM(CASE WHEN RESOLUTION_STATUS IS NULL THEN 1 ELSE 0 END) AS RESOLUTION_STATUS_nulls, SUM(CASE WHEN ACCOUNT_BALANCE_AFTER_TRANSACTION_FLAG IS NULL THEN 1 ELSE 0 END) AS ACCOUNT_BALANCE_AFTER_TRANSACTION_FLAG_nulls, SUM(CASE WHEN LOAN_AMOUNT_FLAG IS NULL THEN 1 ELSE 0 END) AS LOAN_AMOUNT_FLAG_nulls, SUM(CASE WHEN FULL_NAME IS NULL THEN 1 ELSE 0 END) AS FULL_NAME_nulls, SUM(CASE WHEN MINIMUM_PAYMENT_DUE IS NULL THEN 1 ELSE 0 END) AS MINIMUM_PAYMENT_DUE_nulls, SUM(CASE WHEN APPROVAL_REJECTION_DATE IS NULL THEN 1 ELSE 0 END) AS APPROVAL_REJECTION_DATE_nulls, SUM(CASE WHEN CONTACT_NUMBER IS NULL THEN 1 ELSE 0 END) AS CONTACT_NUMBER_nulls, SUM(CASE WHEN TRANSACTION_AMOUNT_FLAG IS NULL THEN 1 ELSE 0 END) AS TRANSACTION_AMOUNT_FLAG_nulls, SUM(CASE WHEN CREDIT_LIMIT IS NULL THEN 1 ELSE 0 END) AS CREDIT_LIMIT_nulls, SUM(CASE WHEN AGE IS NULL THEN 1 ELSE 0 END) AS AGE_nulls FROM banking_data_raw;

// If minimum_payment_due is negative then set it to zero.
UPDATE BANKING_DATA_RAW SET MINIMUM_PAYMENT_DUE = 0 WHERE MINIMUM_PAYMENT_DUE < 0;

// Cleaning GENDER column
UPDATE BANKING_DATA_RAW SET GENDER = CASE 
    WHEN UPPER(GENDER) = 'MALE' OR UPPER(GENDER) = 'M' THEN 'M'
    WHEN UPPER(GENDER) = 'FEMALE' OR UPPER(GENDER) = 'F' THEN 'F'
    ELSE 'O'
END;

// If first name is null then we need to create an anomaly column, If last name is null then it's a valid entry.
// Concatenating first name and last name into full name
ALTER TABLE BANKING_DATA_RAW ADD COLUMN FULL_NAME VARCHAR;
UPDATE BANKING_DATA_RAW SET FULL_NAME = CASE
    WHEN FIRST_NAME IS NOT NULL AND LAST_NAME IS NULL THEN FIRST_NAME
    ELSE FIRST_NAME || ' ' || LAST_NAME
END;

// Checking duplicate rows
SELECT * FROM banking_data_raw
QUALIFY COUNT(*) OVER (PARTITION BY FULL_NAME, CONTACT_NUMBER ORDER BY FULL_NAME) > 1;
// Query produced no results - hence no duplicate rows are there.

// Dropping first name and last name columns
ALTER TABLE BANKING_DATA_RAW DROP COLUMN FIRST_NAME;
ALTER TABLE BANKING_DATA_RAW DROP COLUMN LAST_NAME;
ALTER TABLE BANKING_DATA_RAW DROP COLUMN ANOMALY;

CREATE OR REPLACE PROCEDURE NULL_VALUE_ANOMALIES(COL_NAME STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    FLAG_COL STRING;
    SQL_STMT STRING;
BEGIN
    FLAG_COL := UPPER(COL_NAME) || '_FLAG';

    SQL_STMT := 
        'ALTER TABLE BANKING_DATA_RAW ADD COLUMN IF NOT EXISTS "' 
        || FLAG_COL || '" BOOLEAN';

    EXECUTE IMMEDIATE :SQL_STMT;

    SQL_STMT := 
        'UPDATE BANKING_DATA_RAW SET "' 
        || FLAG_COL || '" = IFF("' 
        || UPPER(COL_NAME) || '" IS NULL, TRUE, FALSE)';

    EXECUTE IMMEDIATE :SQL_STMT;

    RETURN 'Created/updated flag column: ' || FLAG_COL;
END;
$$;

CALL NULL_VALUE_ANOMALIES('FULL_NAME');
CALL NULL_VALUE_ANOMALIES('LOAN_AMOUNT');
CALL NULL_VALUE_ANOMALIES('MINIMUM_PAYMENT_DUE');
CALL NULL_VALUE_ANOMALIES('TRANSACTION_AMOUNT');
CALL NULL_VALUE_ANOMALIES('ACCOUNT_BALANCE');
CALL NULL_VALUE_ANOMALIES('ACCOUNT_BALANCE_AFTER_TRANSACTION');

CREATE OR REPLACE PROCEDURE NEGATIVE_VALUE_ANOMALIES(COL_NAME STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    FLAG_COL STRING;
    SQL_STMT STRING;
BEGIN
    FLAG_COL := UPPER(COL_NAME) || '_FLAG_NEG';

    SQL_STMT := 
        'ALTER TABLE BANKING_DATA_RAW ADD COLUMN IF NOT EXISTS "' 
        || FLAG_COL || '" BOOLEAN';

    EXECUTE IMMEDIATE :SQL_STMT;

    SQL_STMT := 
        'UPDATE BANKING_DATA_RAW SET "' 
        || FLAG_COL || '" = IFF("' 
        || UPPER(COL_NAME) || '" < 0, TRUE, FALSE)';

    EXECUTE IMMEDIATE :SQL_STMT;

    RETURN 'Created/updated flag column: ' || FLAG_COL;
END;
$$;

CALL NEGATIVE_VALUE_ANOMALIES('LOAN_AMOUNT');
CALL NEGATIVE_VALUE_ANOMALIES('TRANSACTION_AMOUNT');

SELECT * FROM BANKING_DATA_RAW limit 10;

CREATE OR REPLACE PROCEDURE Z_SCORE_ANOMALIES(COL_NAME STRING)
RETURNS STRING
LANGUAGE SQL
AS
    $$
    DECLARE
        FLAG_COL STRING;
        SQL_STMT STRING;
    BEGIN
        FLAG_COL := UPPER(COL_NAME) || '_FLAG_Z';

        SQL_STMT := 'ALTER TABLE BANKING_DATA_RAW ADD COLUMN IF NOT EXISTS "' || FLAG_COL || '" BOOLEAN';

        EXECUTE IMMEDIATE :SQL_STMT;

        SQL_STMT := 'UPDATE BANKING_DATA_RAW
            SET "' || FLAG_COL || '" =
                IFF(
                    S.STD_VAL IS NULL 
                    OR S.STD_VAL = 0
                    OR "' || UPPER(COL_NAME) || '" IS NULL,
                    FALSE,
                IFF(
                    ABS(
                         ROUND(("' || UPPER(COL_NAME) || '" - S.AVG_VAL) / S.STD_VAL,2)
                    ) > 3,
                    TRUE,
                    FALSE
                )
            )
            FROM (
                SELECT 
                    AVG("' || UPPER(COL_NAME) || '") AS AVG_VAL,
                    STDDEV("' || UPPER(COL_NAME) || '") AS STD_VAL
                FROM BANKING_DATA_RAW
            ) S';

        EXECUTE IMMEDIATE :SQL_STMT;

        RETURN 'Anomaly flag created: ' || FLAG_COL;
    END;
    $$;
CALL Z_SCORE_ANOMALIES('TRANSACTION_AMOUNT');
CALL Z_SCORE_ANOMALIES('LOAN_AMOUNT');
CALL Z_SCORE_ANOMALIES('ACCOUNT_BALANCE');

ALTER TABLE BANKING_DATA_RAW ADD COLUMN CREDIT_ANOMALY BOOLEAN;
UPDATE BANKING_DATA_RAW T SET CREDIT_ANOMALY = CASE
    WHEN UTILIZATION_RATE > UPPER_BOUND THEN TRUE
    WHEN UTILIZATION_RATE < LOWER_BOUND THEN TRUE
    ELSE FALSE
END
FROM(
    WITH STATS AS(
        SELECT CUSTOMER_ID, (CREDIT_CARD_BALANCE / NULLIF(CREDIT_LIMIT, 0)) AS UTILIZATION_RATE,
        PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY(CREDIT_CARD_BALANCE / NULLIF(CREDIT_LIMIT, 0))) OVER() AS Q1, PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY(CREDIT_CARD_BALANCE / NULLIF(CREDIT_LIMIT, 0))) OVER() AS Q3 FROM BANKING_DATA_RAW
    ),
    BOUNDS AS(
        SELECT CUSTOMER_ID, UTILIZATION_RATE, (Q3 + 1.5*(Q3-Q1)) AS UPPER_BOUND, (Q1 - 1.5*(Q3-Q1)) AS LOWER_BOUND FROM STATS
    )
    SELECT * FROM BOUNDS
) B
WHERE T.CUSTOMER_ID = B.CUSTOMER_ID;

DESC TABLE BANKING_DATA_RAW;

ALTER TABLE BANKING_DATA_RAW ADD COLUMN ANOMALY BOOLEAN;
UPDATE BANKING_DATA_RAW SET ANOMALY = CASE WHEN 
        FULL_NAME_FLAG = 1 OR
        LOAN_AMOUNT_FLAG = 1 OR
        MINIMUM_PAYMENT_DUE_FLAG = 1 OR
        TRANSACTION_AMOUNT_FLAG = 1 OR
        ACCOUNT_BALANCE_FLAG = 1 OR
        ACCOUNT_BALANCE_AFTER_TRANSACTION_FLAG = 1 OR
        LOAN_AMOUNT_FLAG_NEG = 1 OR
        TRANSACTION_AMOUNT_FLAG_NEG = 1 OR
        TRANSACTION_AMOUNT_FLAG_Z = 1 OR
        LOAN_AMOUNT_FLAG_Z = 1 OR
        ACCOUNT_BALANCE_FLAG_Z = 1 OR
        CREDIT_ANOMALY = 1
    THEN 1
    ELSE 0
END;

// anomaly count
SELECT COUNT(*) AS ANOMALY_COUNT FROM BANKING_DATA_RAW WHERE ANOMALY = 1;

// Checking if age is less than 18 or age is more than 100
SELECT * FROM BANKING_DATA_RAW WHERE AGE < 18 OR AGE > 120;

// Checking invalid transactions
SELECT * FROM BANKING_DATA_RAW WHERE TRANSACTION_AMOUNT < 0;