-- Unified customer profile: joins customer, transaction, and loan data with credit utilization and segmentation thresholds

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE BANKING_A;
USE DATABASE BANKDB;
USE SCHEMA BANKDB.BANKSCHEMA;

-- Create unified bank data by joining customer, transaction, and loan tables
CREATE OR REPLACE TABLE UNIFIED_BANK_DATA AS
SELECT
    C.CUSTOMER_ID,
    C.FULL_NAME,
    C.AGE,
    C.GENDER,
    C.ADDRESS,
    C.CITY,
    C.CONTACT_NUMBER,
    C.EMAIL,
    C.ACCOUNT_TYPE,
    C.ACCOUNT_BALANCE,
    C.DATE_OF_ACCOUNT_OPENING,
    C.ANOMALY,

    T.TRANSACTIONID,
    T.LAST_TRANSACTION_DATE,
    T.TRANSACTION_DATE,
    T.TRANSACTION_TYPE,
    T.TRANSACTION_AMOUNT,
    T.ACCOUNT_BALANCE_AFTER_TRANSACTION,

    L.LOAN_ID,
    L.BRANCH_ID,
    L.LOAN_AMOUNT,
    L.LOAN_TYPE,
    L.INTEREST_RATE,
    L.LOAN_TERM,
    L.APPROVAL_REJECTION_DATE,
    L.LOAN_STATUS,
    L.CARDID,
    L.CARD_TYPE,
    L.CREDIT_LIMIT,
    L.CREDIT_CARD_BALANCE,
    L.MINIMUM_PAYMENT_DUE,
    L.PAYMENT_DUE_DATE,
    L.LAST_CREDIT_CARD_PAYMENT_DATE,
    L.REWARDS_POINTS
FROM CUSTOMER C
LEFT JOIN TRANSACTION_TABLE T ON C.CUSTOMER_ID = T.CUSTOMER_ID
LEFT JOIN LOAN L ON T.CUSTOMER_ID = L.CUSTOMER_ID;

-- Add credit utilization percentage to LOAN table
ALTER TABLE LOAN ADD COLUMN CREDIT_UTILIZATION_PERCENTAGE FLOAT;

UPDATE LOAN SET CREDIT_UTILIZATION_PERCENTAGE = CASE
    WHEN CREDIT_LIMIT = 0 THEN NULL
    ELSE (CREDIT_CARD_BALANCE / CREDIT_LIMIT) * 100
END;

-- Add credit utilization percentage to UNIFIED_BANK_DATA table
ALTER TABLE UNIFIED_BANK_DATA ADD COLUMN CREDIT_UTILIZATION_PERCENTAGE FLOAT;

UPDATE UNIFIED_BANK_DATA SET CREDIT_UTILIZATION_PERCENTAGE = CASE
    WHEN CREDIT_LIMIT = 0 THEN NULL
    ELSE (CREDIT_CARD_BALANCE / CREDIT_LIMIT) * 100
END;

-- Compute segmentation thresholds using percentiles
CREATE OR REPLACE TABLE CUSTOMER_SEGMENT_THRESHOLDS AS
SELECT
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY ACCOUNT_BALANCE) AS ACCOUNT_BALANCE_P75,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY ACCOUNT_BALANCE) AS ACCOUNT_BALANCE_P25,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY REWARDS_POINTS) AS REWARDS_POINTS_P75,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY (LOAN_AMOUNT / ACCOUNT_BALANCE) * 100) AS MONEY_ISSUES_P25,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY (LOAN_AMOUNT / ACCOUNT_BALANCE) * 100) AS MONEY_ISSUES_P75
FROM UNIFIED_BANK_DATA;

-- Verify results
SELECT * FROM CUSTOMER_SEGMENT_THRESHOLDS;

SELECT * FROM UNIFIED_BANK_DATA LIMIT 10;